Add WiFi GATT service
CESARBR/knot-gateway-netsetup pull request #10
Opened 2019-07-24 12:49 UTC by ramonhpr

This patch adds a GATT service to set up the WiFi which the gateway will connect with.

2019-07-25 13:29 UTC, vitbaq requested changes
Remove encrypt on pswd characteristic. In this first moment, KNoT setup mobile App is not doing any security process.
Also, it's suggested adding a characteristic that passes a wifi status (e.g. if the gw is connected or not). What do you think?

2019-07-25 13:29 UTC, vitbaq commented on netsetup/srv_gatt_wifi.py
> +                                ["encrypt-write"], service)
Use "write" only.
Currently, the knot app setup is not doing any security process.

2019-07-25 13:31 UTC, ramonhpr commented
@vitbaq I agree with the characteristic status. But I will add it when I make the integration with connman, because it already has a dbus property like that.

2019-08-01 17:06 UTC, vitbaq requested changes
Plz, add the GATT wifi service on the BLE advertisement (line 40, ble.py). If possible, don't use the UUID value directly, use from ser_gatt_wifi.py.

2019-08-07 12:21 UTC, jcorde requested changes

2019-08-07 12:21 UTC, jcorde commented on netsetup/ble_util/characteristic.py
>  import logging
About the commit message for 71ed67a87764754c7015d95d4f4031908aa49c7d

2019-08-07 12:21 UTC, jcorde commented on netsetup/ble_util/characteristic.py
>  import logging
Please, update the title for something more descriptive. Something like `ble: gatt: Allow value update watch` would be more fit.

2019-08-07 12:21 UTC, jcorde commented on netsetup/ble_util/characteristic.py
>  import logging
Typo: 
> the signal propertiesChanged **to** be called

2019-08-07 12:21 UTC, jcorde commented on netsetup/ble_util/characteristic.py
>  import logging
Please, revert:
>  changed by the **service GATT**

2019-08-07 12:21 UTC, jcorde commented on netsetup/ble_util/characteristic.py
> +            logging.error('Invalid value length')
Maybe something like `No value received` would be more appropriated

2019-08-07 12:21 UTC, jcorde commented on netsetup/ble.py
About commit message for b207a3820d740bf30ef12fa93b5abf9ac2963b46

2019-08-07 12:21 UTC, jcorde commented on netsetup/ble.py
> +        self.current_srv_gatt = 0
What is this for?

2019-08-07 12:21 UTC, jcorde commented on netsetup/ble.py
Please, use something like:
> Add `gatt_knot` field to store application being advertised.

2019-08-07 12:21 UTC, jcorde commented on netsetup/ble.py
>  from dbus.service import method as dbus_method
About message for commit 0da7f37960b281803871831b11ba9612f5642bd4

2019-08-07 12:21 UTC, jcorde commented on netsetup/ble.py
>  from dbus.service import method as dbus_method
> patch **adds** a GATT

2019-08-07 12:21 UTC, jcorde commented on netsetup/srv_gatt_wifi.py
> +        logging.info('SSID changed %s' % convert_array_to_str(self.ssid))
Please, use `SSID changed *to* %s`

2019-08-07 12:21 UTC, jcorde commented on netsetup/ble.py
> +        qtd_srv = len(self.gatt_knot.services)
**qtd** sorry yo no hablo portugues

2019-08-07 12:21 UTC, jcorde commented on netsetup/ble.py
> +        self.service_uuids = []
This should be called right after
```
self.ad_manager.UnregisterAdvertisement(
            self.ad_knot,
            reply_handler=lambda: None,
            error_handler=on_error)
```

2019-08-07 12:21 UTC, jcorde commented on netsetup/ble.py
> +    def toogle_uuid(self):
as this does not remove the old UUID, I see this as a `set_next_uuid()`  or something similar

2019-08-07 12:21 UTC, jcorde commented on netsetup/__main__.py
About message for commit c2fb91536142c734a511282c434c4ef14feeaa2c

2019-08-07 12:21 UTC, jcorde commented on netsetup/__main__.py
This patch toggles the service UUIDs in advertisement packet

2019-08-07 12:21 UTC, jcorde commented on netsetup/connman.py
> +#!/usr/bin/env python
About message for commit cecea97f1d5f4d6e1962fa640337e0c22f656d63

Please, explain what connman does.

Also, use a more descriptive title. Something like: Add initial connection manager support.

2019-08-07 12:21 UTC, jcorde commented on netsetup/connman.py
> +    def __init__(self):
Please, place `__init__` as the first function of the class

2019-08-07 12:21 UTC, jcorde commented on netsetup/connman.py
> +        except DBusException as err:  # ignore if connmand is not running
This exception is not only for connman errors. Please, update the comment

2019-08-07 12:21 UTC, jcorde commented on netsetup/connman.py
About message for commit f77f2be6be97cfaff3c09e8e5a0d0f2f583139da

2019-08-07 12:21 UTC, jcorde commented on netsetup/connman.py
This patch **registers** a connman agent to send the password to a wifi
network when **it** is requested to **the** user.

For more **information** about connman agent API see the following link:
https://git.kernel.org/pub/scm/network/connman/connman.git/tree/doc/agent-api.txt

2019-08-07 12:21 UTC, jcorde commented on netsetup/connman.py
> +            response.update({'Passphrase': self.passphrase})
Where did you define `self.passphrase`?

2019-08-07 12:21 UTC, jcorde commented on netsetup/connman.py
> +            response.update({'Passphrase': self.passphrase})
Did you have to?

2019-08-07 12:21 UTC, jcorde commented on netsetup/connman.py
> +            logging.info('Wifi enabled')
You're sending the command to enable the Wi-Fi, but no verification is done. Please, update the logging to something like `'Enabling wifi'` or add a confirmation step before it.

2019-08-07 12:21 UTC, jcorde commented on netsetup/connman.py
> +            logging.error('Unable to get wifi technology. Connman not running')
This check should be done at the constructor.

2019-08-07 12:21 UTC, jcorde commented on netsetup/connman.py
> +            logging.error('Not found technology wifi')
Shouldn't this check be done inside `__get_wifi_technology_path()`?

2019-08-07 12:21 UTC, jcorde commented on netsetup/connman.py
> +            CONNMAN_TECHNOLOGY_INTERFACE)
Why not including 
```
dbus.Interface(
            self.bus.get_object(CONNMAN_SERVICE_NAME, path),
            CONNMAN_TECHNOLOGY_INTERFACE)
```
inside `__get_wifi_technology_path()` and changing its name to `__get_wifi_technology()`?

2019-08-07 12:21 UTC, jcorde commented on netsetup/connman.py
> +    def __enable_wifi(self, iface):
Why calling it `iface` here, but receiving a technology?

2019-08-07 12:21 UTC, jcorde commented on netsetup/connman.py
> +                        return obj_path
Shouldn't a warning be printed in case of not finding wifi technology?

2019-08-07 12:21 UTC, jcorde commented on netsetup/connman.py
> +            on_scan_completed(currentServices)
Please, add a blank line after the function definition

2019-08-07 12:21 UTC, jcorde commented on netsetup/connman.py
>  CONNMAN_SERVICE_NAME = 'net.connman'
About message for commit 7b6690bccb858bba2858e1f80e8fbb3767671afa:

2019-08-07 12:21 UTC, jcorde commented on netsetup/connman.py
>  CONNMAN_SERVICE_NAME = 'net.connman'
Maybe the title could be more descriptive as `connman: Add connect to Wi-Fi support`

2019-08-07 12:21 UTC, jcorde commented on netsetup/connman.py
>  CONNMAN_SERVICE_NAME = 'net.connman'
>This patch adds a method to connect **to** a simple network with SSID and
password.

2019-08-07 12:21 UTC, jcorde commented on netsetup/connman.py
> +    def __get_wifi_service_path(self, name):
Why not including `__get_wifi_service_path(self, name)` as a inner function of `__do_connect(self, path)`, and change it to `__do_connect(self, name)`?

2019-08-07 12:21 UTC, jcorde commented on netsetup/connman.py
> +        for obj_path, properties in self.manager.GetServices():
Please, log in case of not finding the target obj_path

2019-08-07 12:21 UTC, jcorde commented on netsetup/connman.py
> +    def connect_wifi(self, name, password):
This is redundant with `__do_connect()`
Shouldn't this be something like `scan_and_connect_wifi()`?

2019-08-09 21:36 UTC, jcorde approved these changes

2019-08-13 15:45 UTC, merged